import { error, json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { findGame, games, isLanguageId, languagesFor, type GameEntry } from '$lib/data/games';
import type { ScrLibrary } from '$lib/models/library';

/**
 * Serves a game's builtin function library — the documents the extension bundles, kept in step by
 * `npm run sync:api`.
 *
 * Lazy by design. There are eight artifacts totalling ~7.5 MB; statically importing them all would
 * put every byte in the server bundle and pay for it on every cold start, to answer a request that
 * wants one. `import.meta.glob` splits them into separate chunks that load on demand, and the
 * parsed result is held per key afterwards.
 */
const sources = import.meta.glob<{ default: unknown }>('$lib/apiSource/*_api_*.json');

/** Prepared payloads, keyed `<prefix>_<language>`. Built once per key, then reused. */
const cache = new Map<string, Promise<ScrLibrary>>();

/**
 * The four pre-BO3 artifacts are a bare `{ api: [...] }` — only BO3's carry the
 * `gameId`/`languageId`/`revision`/`revisedOn` envelope, because they were generated by a different
 * path. Rather than make every consumer tolerate the difference, the envelope is completed here, so
 * one shape leaves this endpoint regardless of which file answered.
 */
function normalise(raw: unknown, game: GameEntry, languageId: string): ScrLibrary {
	const document = (raw ?? {}) as Partial<ScrLibrary> & { api?: unknown };

	if (!Array.isArray(document.api)) {
		throw new Error(`${game.prefix}_api_${languageId}.json has no api array.`);
	}

	return {
		...document,
		api: document.api,
		gameId: document.gameId ?? game.prefix,
		languageId: document.languageId ?? languageId,
		revision: document.revision ?? 0,
		revisedOn: document.revisedOn ?? null,
		provenance: {
			source: game.source,
			complete: game.complete,
			reliableSignatures: game.reliableSignatures,
			inheritsFrom: game.inheritsFrom ?? null
		}
	} as ScrLibrary;
}

function load(game: GameEntry, languageId: string): Promise<ScrLibrary> {
	const key = `${game.prefix}_${languageId}`;
	const existing = cache.get(key);
	if (existing) {
		return existing;
	}

	const path = `/src/lib/apiSource/${game.prefix}_api_${languageId}.json`;
	const importer = sources[path];
	if (!importer) {
		return Promise.reject(new Error(`No library artifact at ${path}.`));
	}

	const pending = importer()
		.then((module) => normalise(module.default ?? module, game, languageId))
		.catch((cause) => {
			// A failed load must not be remembered, or one bad request poisons the key for the
			// life of the process.
			cache.delete(key);
			throw cause;
		});

	cache.set(key, pending);
	return pending;
}

export const GET = (async ({ url, setHeaders }) => {
	const gameId = url.searchParams.get('gameId');
	const languageId = url.searchParams.get('languageId')?.toLowerCase() ?? '';

	const game = findGame(gameId ?? undefined);
	if (!game) {
		const available = games.map((entry) => entry.slug).join(', ');
		error(400, `Unknown game "${gameId ?? ''}". Available: ${available}.`);
	}

	if (!isLanguageId(languageId) || !languagesFor(game).includes(languageId)) {
		error(
			400,
			`${game.name} has no "${languageId}" library. Available: ${languagesFor(game).join(', ')}.`
		);
	}

	let library: ScrLibrary;
	try {
		library = await load(game, languageId);
	} catch {
		error(404, `No library is published for ${game.name} (${languageId.toUpperCase()}).`);
	}

	// Lets a client ask "is there something newer" without paying for the whole document — the
	// libraries run to 2.9 MB, so a revision check that downloads one is not a check.
	setHeaders({
		ETag: `"${library.gameId}-${library.languageId}-${library.revision}"`,
		'Cache-Control': 'public, max-age=0, must-revalidate'
	});

	if (url.searchParams.get('meta') !== null) {
		const { api, ...envelope } = library;
		return json({ ...envelope, count: api.length });
	}

	return json(library);
}) satisfies RequestHandler;
