// GENERATED by scripts/sync-api.mjs — do not edit. Run `npm run sync:api`.
//
// How many entries each bundled library holds, counted from the artifacts themselves. The home
// page's engine index reads these, so the figure it shows moves when the data does.

export type LibraryCount = { gsc: number; csc: number };

export const libraryCounts: Record<string, LibraryCount> = {
	"bo1": {
		"gsc": 1377,
		"csc": 320
	},
	"cod4": {
		"gsc": 819,
		"csc": 0
	},
	"mw2": {
		"gsc": 1111,
		"csc": 0
	},
	"t7": {
		"gsc": 2191,
		"csc": 803
	},
	"waw": {
		"gsc": 1060,
		"csc": 188
	}
};

/** Every entry across every game and both script VMs. */
export const totalBuiltins = 7869;
