namespace GSCode.Parser.Lexing;

/// <summary>
/// Every kind of token the lexer can produce. Trivia (whitespace, comments) are tokens
/// too — the parser skips them via TokenCursor, while the formatter and semantic tokens
/// read the raw stream. Note: [[ and ]] are NOT lexed as double-bracket tokens; the
/// parser recognizes two adjacent brackets, so nested indexers like a[b[1]] just work.
/// </summary>
public enum TokenKind
{
    // Sentinels
    EndOfFile,
    Error,

    // Trivia
    Whitespace,
    Newline,
    LineComment,
    BlockComment,
    DocComment,

    // Literals and names. Globals (self, level, game, ...) lex as Identifier and are
    // classified downstream, matching engine behavior.
    Identifier,
    Integer,
    Float,
    Hex,
    String,
    LocalizedString,
    HashString,
    AnimReference,

    // Keywords (matched case-insensitively). ORDERING CONTRACT: this block must stay
    // contiguous from Class through ProfileStop — TokenFacts.IsKeyword range-checks it.
    Class,
    Function,
    Var,
    Return,
    Wait,
    WaitTill,
    WaitTillMatch,
    WaitTillFrameEnd,
    WaitRealTime,
    Thread,
    If,
    Else,
    Do,
    While,
    For,
    Foreach,
    In,
    New,
    Switch,
    Case,
    Default,
    Break,
    Continue,
    Notify,
    Endon,
    Assert,
    AssertMsg,
    Constructor,
    Destructor,
    Autoexec,
    Private,
    Const,
    IsDefined,
    Undefined,
    True,
    False,
    VectorScale,
    ProfileStart,
    ProfileStop,

    // Preprocessor directives (matched case-sensitively, lowercase per engine convention)
    UsingDirective,
    InsertDirective,
    DefineDirective,
    NamespaceDirective,
    PrecacheDirective,
    UsingAnimTreeDirective,
    AnimTreeDirective,
    IfDirective,
    ElifDirective,
    ElseDirective,
    EndifDirective,

    // Dev blocks
    DevBlockOpen,
    DevBlockClose,

    // Punctuation
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket,
    Semicolon,
    Comma,
    Dot,
    Ellipsis,
    Colon,
    ScopeResolution,
    QuestionMark,
    Backslash,
    Hash,
    Dollar,
    Arrow,

    // Operators
    Assign,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    Bang,
    LessThan,
    GreaterThan,
    PlusPlus,
    MinusMinus,
    EqualsEquals,
    StrictEquals,
    NotEquals,
    StrictNotEquals,
    LessThanEquals,
    GreaterThanEquals,
    LogicalAnd,
    LogicalOr,
    ShiftLeft,
    ShiftRight,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AmpersandAssign,
    PipeAssign,
    CaretAssign,
    ShiftLeftAssign,
    ShiftRightAssign,
}
