<script lang="ts">
	/**
	 * The slab under the hero: one line of GSC, exploded.
	 *
	 * It replaced an engine index (the five games on a year axis with a builtin count each). That
	 * band said how MUCH the extension knew; this one shows WHAT it knows, which is the harder claim
	 * and the one nothing else on the page makes. The total builtin count survives in the footer
	 * readout, still generated by `npm run sync:api`.
	 *
	 * The hero says what the tool is; this shows how much of a single line it understands. Each
	 * annotated token has a leader running down to a callout, the way a drawing labels its parts —
	 * the same register as the crosshair and the corner handles above it. There is one line per
	 * game, cycling, so the multi-game claim is made by example rather than stated: the CoD4 line
	 * reaches a function by path, the Black Ops III line by namespace, and the WaW and MW2 lines
	 * carry their provenance in the callout instead of pretending to a certainty they do not have.
	 *
	 * Leaders are measured, not drawn by hand: token and callout centres are read after layout and
	 * on resize, so the picture holds at any width the row still fits. Below md the leaders go and
	 * the callouts fall back to a numbered list keyed to superscripts on the line.
	 */
	import { tick } from 'svelte';
	import { findGame } from '$lib/data/games';
	import { totalBuiltins } from '$lib/data/libraryCounts';
	import { reducedMotion } from '$lib/actions/reveal';

	let { active = false }: { active?: boolean } = $props();

	type Callout = { kind: string; value: string; note: string };
	type Segment = { text: string; tone?: 'punct' | 'string' | 'keyword'; callout?: Callout };
	type Line = { game: string; segments: Segment[] };

	const lines: Line[] = [
		{
			game: 'bo3',
			segments: [
				{ text: 'self', callout: { kind: 'Entity', value: 'self · player', note: 'from the function’s call sites' } },
				{ text: ' ' },
				{ text: 'thread', tone: 'keyword' },
				{ text: ' ' },
				{
					text: 'zm_powerups',
					callout: { kind: 'Namespace', value: '#using scripts\\zm\\_zm_powerups', note: 'resolved through the mod folder' }
				},
				{ text: '::', tone: 'punct' },
				{
					text: 'specific_powerup_drop',
					callout: { kind: 'Function', value: '( powerup_name, origin )', note: 'script-defined · go to definition' }
				},
				{ text: '( ', tone: 'punct' },
				{ text: '"nuke"', tone: 'string' },
				{ text: ', ', tone: 'punct' },
				{ text: 'self.origin', callout: { kind: 'Field', value: 'vector', note: 'engine object-field data' } },
				{ text: ' );', tone: 'punct' }
			]
		},
		{
			game: 'cod4',
			segments: [
				{ text: 'self', callout: { kind: 'Entity', value: 'self · entity', note: 'from the function’s call sites' } },
				{ text: ' ' },
				{ text: 'thread', tone: 'keyword' },
				{ text: ' ' },
				{
					text: 'maps\\_utility',
					callout: { kind: 'Path call', value: 'raw\\maps\\_utility.gsc', note: 'no #include needed for a qualified call' }
				},
				{ text: '::', tone: 'punct' },
				{
					text: 'play_sound_in_space',
					callout: { kind: 'Function', value: '( alias, origin )', note: 'script-defined · 2 params' }
				},
				{ text: '( ', tone: 'punct' },
				{ text: '"elm_quiet_nice"', tone: 'string' },
				{ text: ', ', tone: 'punct' },
				{ text: 'self.origin', callout: { kind: 'Field', value: 'vector', note: 'engine object-field data' } },
				{ text: ' );', tone: 'punct' }
			]
		},
		{
			game: 'waw',
			segments: [
				{ text: 'self', callout: { kind: 'Entity', value: 'self · player', note: 'from the function’s call sites' } },
				{ text: ' ' },
				{
					text: 'setclientdvar',
					callout: { kind: 'Builtin', value: '( dvar, value )', note: 'WaW wordfile · signature from CoD4' }
				},
				{ text: '( ', tone: 'punct' },
				{ text: '"ui_hud_hardcore"', tone: 'string', callout: { kind: 'String', value: 'dvar name', note: 'completion from known dvars' } },
				{ text: ', ', tone: 'punct' },
				{ text: '1', callout: { kind: 'Literal', value: 'int', note: '' } },
				{ text: ' );', tone: 'punct' }
			]
		},
		{
			game: 'mw2',
			segments: [
				{ text: 'self', callout: { kind: 'Entity', value: 'self · player', note: 'from the function’s call sites' } },
				{ text: ' ' },
				{
					text: 'iprintlnbold',
					callout: { kind: 'Builtin', value: '( message, … )', note: 'MW2 · reconstructed from shipped scripts' }
				},
				{ text: '( ', tone: 'punct' },
				{
					text: '&"PLATFORM_HOLD_TO_ACTIVATE"',
					tone: 'string',
					callout: { kind: 'Localised', value: 'localized string', note: 'looked up in the string tables' }
				},
				{ text: ' );', tone: 'punct' }
			]
		},
		{
			game: 'bo1',
			segments: [
				{ text: 'zombies', callout: { kind: 'Local', value: 'array of entity', note: 'inferred from the assignment' } },
				{ text: ' = ', tone: 'punct' },
				{
					text: 'getaiarray',
					callout: { kind: 'Builtin', value: '( team, … )', note: 'BO1 wordfile · signature from CoD4' }
				},
				{ text: '( ', tone: 'punct' },
				{ text: '"axis"', tone: 'string', callout: { kind: 'String', value: 'team name', note: '' } },
				{ text: ' );', tone: 'punct' }
			]
		}
	];

	let index = $state(0);
	let fading = $state(false);
	let hovered = $state<number | null>(null);
	/** Set once the visitor picks a game; auto-rotation stops so the picture holds still. */
	let pinned = $state(false);

	const line = $derived(lines[index]);
	const game = $derived(findGame(line.game));
	const callouts = $derived(
		line.segments.flatMap((segment, i) => (segment.callout ? [{ ...segment.callout, at: i }] : []))
	);

	function show(next: number) {
		if (next === index) return;
		if (reducedMotion()) {
			index = next;
			return;
		}
		fading = true;
		setTimeout(() => {
			index = next;
			fading = false;
		}, 180);
	}

	// Rotate every few seconds while in view and unpinned.
	$effect(() => {
		if (!active || pinned || reducedMotion()) return;
		const id = setInterval(() => show((index + 1) % lines.length), 6500);
		return () => clearInterval(id);
	});

	// ── Leaders ────────────────────────────────────────────────────────────────────────────────
	let frame = $state<HTMLElement | undefined>();
	let tokenEls = $state<(HTMLElement | undefined)[]>([]);
	let calloutEls = $state<(HTMLElement | undefined)[]>([]);
	let leaders = $state<{ d: string; x0: number; y0: number; x1: number; y1: number }[]>([]);
	let size = $state({ w: 0, h: 0 });

	function measure() {
		if (!frame) return;
		const box = frame.getBoundingClientRect();
		size = { w: box.width, h: box.height };
		leaders = callouts.flatMap((c, i) => {
			const t = tokenEls[c.at];
			const k = calloutEls[i];
			if (!t || !k) return [];
			const tb = t.getBoundingClientRect();
			const kb = k.getBoundingClientRect();
			const x0 = tb.left + tb.width / 2 - box.left;
			const y0 = tb.bottom - box.top + 4;
			const x1 = kb.left + 12 - box.left;
			const y1 = kb.top - box.top - 2;
			const drop = 14;
			const d = `M${x0},${y0} V${y0 + drop} L${x1},${y1 - drop} V${y1}`;
			return [{ d, x0, y0, x1, y1 }];
		});
	}

	$effect(() => {
		// Re-measure whenever the line changes, after the new spans exist.
		void index;
		void fading;
		tick().then(measure);
	});

	$effect(() => {
		if (!frame) return;
		const ro = new ResizeObserver(() => measure());
		ro.observe(frame);
		document.fonts?.ready.then(measure);
		return () => ro.disconnect();
	});
</script>

<section class="bg-popover border-border relative border-b" aria-labelledby="exploded-line">
	<div class="lit-grid pointer-events-none absolute inset-0 opacity-40" aria-hidden="true"></div>

	<div class="relative mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:py-20">
		<div class="flex flex-wrap items-end justify-between gap-x-6 gap-y-4">
			<div>
				<p class="type-label text-primary">One line, resolved</p>
				<h2
					id="exploded-line"
					class="text-foreground mt-3 max-w-[22ch] text-heading font-semibold tracking-heading"
				>
					What the server knows about a single line
				</h2>
			</div>
			<!-- Game picker: the five games as ticks; the active one is lit. -->
			<ol class="flex items-baseline gap-4" aria-label="Show a line from">
				{#each lines as l, i (l.game)}
					{@const g = findGame(l.game)}
					<li>
						<button
							type="button"
							class="group focus-visible:outline-ring flex items-baseline gap-1.5 font-mono text-2xs tracking-data transition-colors focus-visible:outline-2 focus-visible:outline-offset-4
								{i === index ? 'text-foreground' : 'text-dim hover:text-muted-foreground'}"
							aria-pressed={i === index}
							onclick={() => {
								pinned = true;
								show(i);
							}}
						>
							<i
								aria-hidden="true"
								class="block size-[5px] border-[1.5px] {i === index ? 'border-primary bg-primary' : 'border-steel'}"
							></i>
							{g?.shortName}
						</button>
					</li>
				{/each}
			</ol>
		</div>

		<div
			bind:this={frame}
			class="relative mt-12 transition-opacity duration-200 lg:mt-16 {fading ? 'opacity-0' : 'opacity-100'}"
		>
			<!-- The line. -->
			<p
				class="font-mono text-foreground overflow-x-auto py-1 text-lg leading-tight whitespace-nowrap sm:text-xl lg:text-2xl xl:text-3xl"
				aria-label="Example line of {game?.name} script"
			>
				{#each line.segments as segment, i (index + ':' + i)}
					{@const n = callouts.findIndex((c) => c.at === i)}
					{#if segment.callout}
						<span
							bind:this={tokenEls[i]}
							class="relative inline-block transition-colors {hovered === n ? 'text-primary' : ''}"
						>
							{segment.text}<sup class="text-dim ml-0.5 text-[0.55em] font-normal md:hidden">{n + 1}</sup>
						</span>
					{:else}
						<span
							class={segment.tone === 'punct'
								? 'text-muted-foreground'
								: segment.tone === 'keyword'
									? 'text-primary'
									: segment.tone === 'string'
										? 'text-muted-foreground'
										: ''}>{segment.text}</span
						>
					{/if}
				{/each}
			</p>

			<!-- Leaders, drawn between the measured points. -->
			<svg
				aria-hidden="true"
				class="pointer-events-none absolute inset-0 hidden md:block"
				width={size.w}
				height={size.h}
				viewBox="0 0 {size.w} {size.h}"
			>
				{#each leaders as l, i (i)}
					<path
						d={l.d}
						fill="none"
						class="transition-colors {hovered === i ? 'stroke-primary' : 'stroke-steel'}"
						stroke-width="1"
					/>
					<rect x={l.x0 - 2.5} y={l.y0 - 2.5} width="5" height="5" class="fill-background stroke-primary" stroke-width="1.5" />
					<rect x={l.x1 - 2.5} y={l.y1 - 2.5} width="5" height="5" class="fill-background {hovered === i ? 'stroke-primary' : 'stroke-steel'}" stroke-width="1.5" />
				{/each}
			</svg>

			<!-- Callouts: one column per annotated token, in token order. -->
			<ol
				class="mt-14 grid gap-x-8 gap-y-6 md:mt-[84px]"
				style={`grid-template-columns:repeat(${Math.min(callouts.length, 2)},minmax(0,1fr))`}
			>
				{#each callouts as c, i (index + ':' + i)}
					<li
						bind:this={calloutEls[i]}
						class="min-w-0"
						onmouseenter={() => (hovered = i)}
						onmouseleave={() => (hovered = null)}
					>
						<p class="type-label {hovered === i ? 'text-primary' : 'text-dim'} transition-colors">
							<span class="md:hidden">{i + 1} · </span>{c.kind}
						</p>
						<p class="text-foreground mt-2 truncate font-mono text-sm lg:text-base">{c.value}</p>
						{#if c.note}
							<p class="text-muted-foreground mt-1.5 text-sm leading-normal font-light">{c.note}</p>
						{/if}
					</li>
				{/each}
			</ol>
		</div>

		<div class="border-border mt-12 flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2 border-t pt-4 lg:mt-16">
			<p class="type-label text-dim">
				{game?.name} · {game?.year} ·
				{game?.imports === 'using' ? '#using · namespaces' : '#include · path calls'}
			</p>
			<p class="type-label text-dim">
				<span class="text-foreground tabular-nums">{totalBuiltins.toLocaleString('en-GB')}</span> engine functions
				bundled · five games · GSC · CSC
			</p>
		</div>
	</div>
</section>

<style>
	@media (min-width: 48rem) {
		ol.grid {
			grid-template-columns: none !important;
			grid-auto-columns: minmax(0, 1fr);
			grid-auto-flow: column;
		}
	}
</style>
