<script lang="ts">
	import { Separator } from '$components/ui/separator/index.js';
	import { Button } from '$components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import * as Sidebar from '$components/ui/sidebar/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import VirtualList from '$lib/components/ui/virtual-list/VirtualList.svelte';

	import Command from '@lucide/svelte/icons/command';
	import Search from '@lucide/svelte/icons/search';
	import Upload from '@lucide/svelte/icons/upload';
	import Download from '@lucide/svelte/icons/download';
	import Save from '@lucide/svelte/icons/save';
	import FolderOpen from '@lucide/svelte/icons/folder-open';
	import Plus from '@lucide/svelte/icons/plus';
	import Undo2 from '@lucide/svelte/icons/undo-2';
	import X from '@lucide/svelte/icons/x';

	import EditorFilters from './EditorFilters.svelte';
	import type { ScrFunction } from '$lib/models/library';
	import { getEditorContext } from '$lib/api-editor/editor.svelte';
	import { ScrLibrarySchema } from '$lib/models/library';

	const truncateString = (string = '', maxLength = 20) =>
		string.length > maxLength ? `${string.substring(0, maxLength)}…` : string;
	const SIDEBAR_ROW_HEIGHT = 32;

	let editor = getEditorContext();
	let library = $derived(editor.library);
	let stats = $derived(editor.stats);
	let hasLibrary = $derived(editor.hasLibrary);
	let selectedFunction = $derived(editor.selectedFunction);
	let totalFunctionCount = $derived(
		stats.verifiedCount + stats.processedCount + stats.autogeneratedCount + stats.newCount
	);
	let verifiedPercent = $derived(
		totalFunctionCount > 0 ? Math.round((stats.verifiedCount / totalFunctionCount) * 100) : 0
	);

	let loadingSource: string | null = $state(null);
	let loadPopoverOpen = $state(false);

	let searchTerm = $state('');

	// Filter state
	let showVerified = $state(true);
	let showProcessed = $state(true);
	let showAutogenerated = $state(true);
	let showProblems = $state(true);
	let showBadVerifications = $state(true);
	let showDeleted = $state(true);

	let filteredEntries = $derived.by(() => {
		// Capture dependencies synchronously at the top
		const search = searchTerm;
		const filterVerified = showVerified;
		const filterProcessed = showProcessed;
		const filterAutogenerated = showAutogenerated;
		const filterProblems = showProblems;
		const filterBadVerifications = showBadVerifications;
		const filterDeleted = showDeleted;
		const fnMap = editor.functions;

		if (!fnMap) {
			return [];
		}

		let w = search.replace(/[.+^${}()|[\]\\]/g, '\\$&'); // regexp escape
		const re = new RegExp(`^${w.replace(/\*/g, '.*').replace(/\?/g, '.')}$`, 'i');

		// When problem/bad-verification filters are off, we need isInvalid per entry.
		// To avoid subscribing to every function's deep validation state, only compute
		// validation when those filters are actually hiding things.
		const needsValidation = !filterProblems || !filterBadVerifications;

		return Array.from(fnMap.values()).filter((functionEditor) => {
			const apiFunction = functionEditor.function;

			// Text search filter
			const matchesSearch =
				apiFunction.name.toLowerCase().includes(search.toLowerCase()) ||
				re.test(apiFunction.name);

			if (!matchesSearch) return false;

			// Deleted filter - check first as it's a distinct state
			if (functionEditor.deleted) return filterDeleted;

			// Read flags directly to minimize reactive subscriptions
			const flags = apiFunction.flags;
			const isVerified = flags.includes('verified');
			const isProcessed = flags.includes('processed');

			// Only compute validation when filters require it
			if (needsValidation) {
				const isInvalid = functionEditor.isInvalid;
				if (isVerified && isInvalid) return filterBadVerifications;
				if (isInvalid) return filterProblems;
			}

			if (isVerified) return filterVerified;
			if (isProcessed) return filterProcessed;
			if (!isVerified && !isProcessed) return filterAutogenerated;

			return true;
		});
	});

	let inputElement: HTMLInputElement | null = $state(null);
	function handleKeyDown(event: KeyboardEvent) {
		if (event.key === 'k' && (event.ctrlKey || event.metaKey) && inputElement) {
			event.preventDefault();
			inputElement.focus();
		}
	}

	let fileInputElement: HTMLInputElement | null = $state(null);

	function handleLoadFromJSON() {
		if (stats.editedCount > 0) {
			const confirmLoad = confirm(
				'You have unsaved changes. Loading a new JSON will overwrite your current progress. Are you sure?'
			);
			if (!confirmLoad) return;
		}
		fileInputElement?.click();
	}

	async function onFileSelected(event: Event) {
		const target = event.target as HTMLInputElement;
		const file = target.files?.[0];
		if (!file) {
			return;
		}

		try {
			const text = await file.text();
			const json = JSON.parse(text);
			const validatedLibrary = await ScrLibrarySchema.parseAsync(json);
			editor.updateLibrary(validatedLibrary);
			// Reset the input so the same file can be selected again
			target.value = '';
		} catch (err) {
			console.error('Failed to load JSON:', err);
			alert('Failed to load JSON. Please ensure it follows the correct schema.');
		}
	}

	function handleSaveToJSON() {
		const exportedLibrary = editor.exportLibrary();
		if (!exportedLibrary) return;

		// Convert dates back to strings for JSON
		const json = JSON.stringify(
			{
				...exportedLibrary,
				revisedOn: exportedLibrary.revisedOn.toISOString()
			},
			null,
			4
		);

		const blob = new Blob([json], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${exportedLibrary.gameId}_api_${exportedLibrary.languageId}.json`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);

		// Reset original state of all function editors to the newly saved state
		// This clears the "edited" flag for all functions
		editor.commitSavedLibrary(exportedLibrary);
	}

	async function loadFromApiSource(languageId: 'gsc' | 'csc') {
		if (stats.editedCount > 0) {
			const confirmLoad = confirm(
				'You have unsaved changes. Loading a new library will overwrite your current progress. Are you sure?'
			);
			if (!confirmLoad) return;
		}

		loadingSource = languageId;
		try {
			const res = await fetch(`/api/getLibrary?gameId=t7&languageId=${languageId}`);
			if (!res.ok) {
				throw new Error(`Failed to load ${languageId.toUpperCase()} library`);
			}
			const json = await res.json();
			const validatedLibrary = await ScrLibrarySchema.parseAsync(json);
			editor.updateLibrary(validatedLibrary);
		} catch (err) {
			console.error('Failed to load API source:', err);
			alert(`Failed to load ${languageId.toUpperCase()} library. Please try again.`);
		} finally {
			loadingSource = null;
		}
	}

	function handleSelectFunction(name: string) {
		editor.selectFunction(name);
	}

	function handleCreateFunction() {
		editor.createFunction();
	}

	function handleRestoreFunction(name: string, event: Event) {
		event.stopPropagation();
		editor.restoreFunction(name);
	}

	function handleUnloadLibrary() {
		if (stats.editedCount > 0) {
			const confirmUnload = confirm(
				'You have unsaved changes. Unloading will discard all your edits. Are you sure?'
			);
			if (!confirmUnload) return;
		}
		editor.unloadLibrary();
	}
</script>

<input
	type="file"
	accept="application/json"
	bind:this={fileInputElement}
	onchange={onFileSelected}
	class="hidden"
/>

<Sidebar.Root side="left" collapsible="offcanvas" variant="sidebar" class="absolute h-full">
	<Sidebar.Header class="border-border gap-3 border-b px-5 py-5">
		<div class="flex shrink-0 flex-col gap-3">
			<div class="type-label text-primary">API Editor</div>
			{#if hasLibrary && library}
				<dl class="flex flex-col gap-1 font-mono text-[11px]">
					<div class="flex items-baseline justify-between gap-3">
						<dt class="type-label text-dim">Language</dt>
						<dd class="text-foreground">{library.languageId}</dd>
					</div>
					<div class="flex items-baseline justify-between gap-3">
						<dt class="type-label text-dim">Game</dt>
						<dd class="text-foreground">{library.gameId}</dd>
					</div>
					<div class="flex items-baseline justify-between gap-3">
						<dt class="type-label text-dim">Revision</dt>
						<dd class="text-foreground">{library.revision}</dd>
					</div>
					<div class="flex items-baseline justify-between gap-3">
						<dt class="type-label text-dim">Revised</dt>
						<dd class="text-foreground">{library.revisedOn.toLocaleDateString()}</dd>
					</div>
				</dl>
			{:else}
				<p class="text-muted-foreground text-xs">No library loaded.</p>
			{/if}
		</div>
	</Sidebar.Header>
	<Sidebar.Content class="flex min-h-0 grow flex-col items-stretch gap-4 px-5 py-5">
		{#if hasLibrary}
			<div>
				<div class="type-label text-dim mb-2.5">Report</div>
				<dl class="flex flex-col gap-1 font-mono text-[11px]">
					<div class="flex items-baseline justify-between gap-3">
						<dt class="text-muted-foreground">Verified</dt>
						<dd class="text-foreground">{stats.verifiedCount}</dd>
					</div>
					<div class="flex items-baseline justify-between gap-3">
						<dt class="text-muted-foreground">Processed</dt>
						<dd class="text-foreground">{stats.processedCount}</dd>
					</div>
					<div class="flex items-baseline justify-between gap-3">
						<dt class="text-muted-foreground">Autogenerated</dt>
						<dd class="text-foreground">{stats.autogeneratedCount}</dd>
					</div>
				</dl>
				<div class="mt-3 flex flex-col gap-1.5">
					<div class="flex items-baseline justify-between font-mono text-[11px]">
						<span class="type-label text-dim">Verified</span>
						<span class="text-primary">{verifiedPercent}%</span>
					</div>
					<div class="bg-recess inset-edge h-[6px] w-full">
						<div
							class="bg-primary h-full transition-[width] duration-300 ease-out"
							style={`width: ${verifiedPercent}%`}
						></div>
					</div>
					<div class="text-dim font-mono text-[10px] tracking-[.08em]">
						{stats.verifiedCount} / {totalFunctionCount} verified
					</div>
				</div>
			</div>
			<Separator />
			<div class="flex min-h-0 grow flex-col">
				<div class="mb-2 flex items-center justify-between">
					<div class="type-label text-dim">Functions</div>
					<Button
						variant="ghost"
						size="icon-xs"
						title="Add new function"
						onclick={handleCreateFunction}
					>
						<Plus />
						<span class="sr-only">Add new function</span>
					</Button>
				</div>
				<div class="-mx-2 min-h-0 w-[calc(100%+1rem)] max-w-full grow">
					<VirtualList items={filteredEntries} itemHeight={SIDEBAR_ROW_HEIGHT} height="100%">
						{#snippet children({ item: fnEditor })}
							{@const apiFunction = fnEditor.function}
							{@const isSelected = selectedFunction === apiFunction.name.toLowerCase()}
							{@const isDeleted = fnEditor.deleted}
							{@const fnFlags = apiFunction.flags}
							<div class="flex h-8 items-center gap-0.5 pr-1">
								<button
									type="button"
									class="nav-item flex h-8 min-w-0 flex-1 items-center gap-2 px-2.5 text-left font-mono text-xs {isSelected
										? 'nav-item-active'
										: 'hover:nav-item-hover'} {isDeleted ? 'opacity-45' : ''}"
									onclick={() => !isDeleted && handleSelectFunction(apiFunction.name)}
									disabled={isDeleted}
								>
									{#if isDeleted}
										<i
											aria-hidden="true"
											class="bg-steel block size-[6px] shrink-0"
											title="This function is marked for deletion"
										></i>
									{:else if fnEditor.isNew}
										<i
											aria-hidden="true"
											class="bg-bright block size-[6px] shrink-0"
											title="This is a new function"
										></i>
									{:else if fnFlags.includes('verified')}
										<i
											aria-hidden="true"
											class="bg-primary block size-[6px] shrink-0"
											title="This function is verified"
										></i>
									{:else if fnFlags.includes('processed')}
										<i
											aria-hidden="true"
											class="bg-steel block size-[6px] shrink-0"
											title="This function was batch-processed"
										></i>
									{:else}
										<i
											aria-hidden="true"
											class="border-steel block size-[6px] shrink-0 border"
											title="This function is unverified"
										></i>
									{/if}
									<span class="truncate {isDeleted ? 'line-through' : ''}">
										{truncateString(apiFunction.name, 25)}
									</span>
								</button>
								{#if isDeleted}
									<Button
										variant="ghost"
										size="icon-xs"
										title="Restore function"
										onclick={() => editor.restoreFunction(apiFunction.name)}
									>
										<Undo2 />
										<span class="sr-only">Restore function</span>
									</Button>
								{/if}
							</div>
						{/snippet}
					</VirtualList>
				</div>
			</div>

			<div class="flex shrink-0 gap-2">
				<div class="relative w-full">
					<Search
						class="text-dim pointer-events-none absolute top-[50%] left-3 size-3.5 -translate-y-[50%]"
					/>
					<Input
						type="search"
						placeholder="Search"
						class="h-9 pr-14 pl-9 text-xs"
						bind:value={searchTerm}
						bind:ref={inputElement}
					/>
					<span
						class="chip-cut text-dim bg-card pointer-events-none absolute top-[50%] right-2 flex -translate-y-[50%] items-center gap-1 px-1.5 py-1 font-mono text-[10px]"
					>
						<Command class="size-3" />
						K
					</span>
				</div>
				<EditorFilters
					bind:showVerified
					bind:showProcessed
					bind:showAutogenerated
					bind:showProblems
					bind:showBadVerifications
					bind:showDeleted
				/>
			</div>
			<Separator />
		{/if}
		<div>
			<div class="type-label text-dim mb-2.5">Actions</div>
			{#if hasLibrary}
				<div class="text-muted-foreground mb-2.5 font-mono text-[11px]">
					{#if stats.editedCount > 0}
						{stats.editedCount} function{stats.editedCount === 1 ? '' : 's'} edited
					{:else}
						No changes applied
					{/if}
				</div>
			{/if}
			<div class="flex gap-2">
				<Popover.Root bind:open={loadPopoverOpen}>
					<Popover.Trigger>
						{#snippet child({ props })}
							<Button size="sm" class="flex-1" disabled={loadingSource !== null} {...props}>
								<FolderOpen />
								{loadingSource ? 'Loading' : 'Load'}
							</Button>
						{/snippet}
					</Popover.Trigger>
					<Popover.Content class="w-52 gap-0" align="start">
						<div class="flex flex-col">
							<button
								type="button"
								class="text-muted-foreground hover:text-foreground -mx-2 flex items-center gap-2.5 px-2 py-2 text-left font-mono text-xs transition-colors hover:bg-[var(--wash-hover)]"
								onclick={() => {
									loadFromApiSource('gsc');
									loadPopoverOpen = false;
								}}
							>
								<Download class="size-3.5" />
								Load latest GSC
							</button>
							<button
								type="button"
								class="text-muted-foreground hover:text-foreground -mx-2 flex items-center gap-2.5 px-2 py-2 text-left font-mono text-xs transition-colors hover:bg-[var(--wash-hover)]"
								onclick={() => {
									loadFromApiSource('csc');
									loadPopoverOpen = false;
								}}
							>
								<Download class="size-3.5" />
								Load latest CSC
							</button>
							<Separator class="my-1.5" />
							<button
								type="button"
								class="text-muted-foreground hover:text-foreground -mx-2 flex items-center gap-2.5 px-2 py-2 text-left font-mono text-xs transition-colors hover:bg-[var(--wash-hover)]"
								onclick={() => {
									handleLoadFromJSON();
									loadPopoverOpen = false;
								}}
							>
								<Upload class="size-3.5" />
								Load from file
							</button>
						</div>
					</Popover.Content>
				</Popover.Root>
				<Button
					variant="secondary"
					size="sm"
					onclick={handleSaveToJSON}
					class="flex-1"
					disabled={!hasLibrary}
				>
					<Save />
					Download
				</Button>
			</div>
			{#if hasLibrary}
				<div class="mt-2 flex gap-2">
					<Button variant="outline" size="sm" onclick={handleUnloadLibrary} class="flex-1">
						<X />
						Unload
					</Button>
				</div>
			{/if}
		</div>
	</Sidebar.Content>

	<Sidebar.Footer
		class="border-border text-dim inline-flex shrink-0 justify-between border-t px-5 py-4 font-mono text-[11px]"
	>
		A part of the GSCode project.
		<a
			href="https://ko-fi.com/blakintosh"
			target="_blank"
			rel="noreferrer"
			class="text-primary hover:text-bright transition-colors"
		>
			Donate
		</a>
	</Sidebar.Footer>

	<Sidebar.Rail />
</Sidebar.Root>

<svelte:window onkeydown={handleKeyDown} />
