<script lang="ts">
	import { Separator } from '$components/ui/separator/index.js';
	import { ScrollArea } from '$components/ui/scroll-area/index.js';
	import { Button } from '$components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import * as Sidebar from '$components/ui/sidebar/index.js';

	// @ts-ignore
	import Command from 'lucide-svelte/icons/command';
	// @ts-ignore
	import Search from 'lucide-svelte/icons/search';

	import LanguageRadio from './drawer/LanguageRadio.svelte';
	import EditorFilters from './EditorFilters.svelte';
	import type { ScrFunction, ScrLibrary } from '$lib/models/library';
	import { page } from '$app/stores';
	import { ApiLibrarian } from '$lib/app/library/api.svelte';
	import { goto } from '$app/navigation';
	import { getEditorContext } from '$lib/api-editor/editor.svelte';
	import { ScrLibrarySchema } from '$lib/models/library';

	const truncateString = (string = '', maxLength = 20) =>
		string.length > maxLength ? `${string.substring(0, maxLength)}…` : string;

	let librarian: ApiLibrarian = $state($page.data.librarian);

	let editor = getEditorContext();
	let library = $derived(editor.library);
	let stats = $derived(editor.stats);

	async function onLanguageChange(value: string | undefined) {
		if (!value) {
			return;
		}

		librarian.languageId = value;
		await goto(`/editor/${value}`);
	}

	let searchTerm = $state('');

	// Filter state
	let showVerified = $state(true);
	let showAutogenerated = $state(true);
	let showProblems = $state(true);
	let showBadVerifications = $state(true);

	let filteredData = $derived.by(() => {
		// Capture dependencies synchronously at the top
		const search = searchTerm;
		const filterVerified = showVerified;
		const filterAutogenerated = showAutogenerated;
		const filterProblems = showProblems;
		const filterBadVerifications = showBadVerifications;

		let w = search.replace(/[.+^${}()|[\]\\]/g, '\\$&'); // regexp escape
		const re = new RegExp(`^${w.replace(/\*/g, '.*').replace(/\?/g, '.')}$`, 'i');
		const resolvedLibrary = library;

		return {
			entries: resolvedLibrary.api.filter((apiFunction: ScrFunction) => {
				// Text search filter
				const matchesSearch =
					apiFunction.name.toLowerCase().includes(search.toLowerCase()) ||
					re.test(apiFunction.name);

				if (!matchesSearch) return false;

				// Category filters
				const functionEditor = editor.getFunction(apiFunction.name);
				if (!functionEditor) return true;

				const isInvalid = functionEditor.isInvalid;
				const isVerified = functionEditor.isVerified;
				const isUnverified = functionEditor.isUnverified;

				// Filter logic: match the visual hierarchy
				if (isVerified && isInvalid) return filterBadVerifications;
				if (isInvalid) return filterProblems;
				if (isVerified) return filterVerified;
				if (isUnverified) return filterAutogenerated;

				return true;
			}),
			languageId: resolvedLibrary.languageId
		};
	});

	let inputElement: HTMLInputElement | null = $state(null);
	function handleKeyDown(event: KeyboardEvent) {
		if (event.key === 'k' && (event.ctrlKey || event.metaKey) && inputElement) {
			event.preventDefault();
			inputElement.focus();
		}
	}

	let fileInputElement: HTMLInputElement | null = $state(null);

	function handleLoadFromJSON() {
		if (stats.editedCount > 0) {
			const confirmLoad = confirm(
				'You have unsaved changes. Loading a new JSON will overwrite your current progress. Are you sure?'
			);
			if (!confirmLoad) return;
		}
		fileInputElement?.click();
	}

	async function onFileSelected(event: Event) {
		const target = event.target as HTMLInputElement;
		const file = target.files?.[0];
		if (!file) {
			return;
		}

		try {
			const text = await file.text();
			const json = JSON.parse(text);
			const validatedLibrary = await ScrLibrarySchema.parseAsync(json);
			editor.updateLibrary(validatedLibrary);
			// Reset the input so the same file can be selected again
			target.value = '';
		} catch (err) {
			console.error('Failed to load JSON:', err);
			alert('Failed to load JSON. Please ensure it follows the correct schema.');
		}
	}

	function handleSaveToJSON() {
		const exportedLibrary = editor.exportLibrary();
		// Convert dates back to strings for JSON
		const json = JSON.stringify(
			{
				...exportedLibrary,
				revisedOn: exportedLibrary.revisedOn.toISOString()
			},
			null,
			4
		);

		const blob = new Blob([json], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${exportedLibrary.gameId}_api_${exportedLibrary.languageId}.json`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);

		// Reset original state of all function editors to the newly saved state
		// This clears the "edited" flag for all functions
		editor.updateLibrary(exportedLibrary);
	}

	function handleBeforeUnload(event: BeforeUnloadEvent) {
		if (stats.editedCount > 0) {
			event.preventDefault();
			event.returnValue = ''; // Required for some browsers
			return '';
		}
	}
</script>

<input
	type="file"
	accept="application/json"
	bind:this={fileInputElement}
	onchange={onFileSelected}
	class="hidden"
/>

<Sidebar.Root side="left" collapsible="offcanvas" variant="sidebar" class="absolute h-full">
	<Sidebar.Header class="px-4 py-4">
		<div class="flex flex-col gap-2 shrink-0">
			<div class="font-medium text-sm">Editor</div>
			<div class="flex flex-col gap-1 text-[10px] uppercase tracking-wider text-muted-foreground">
				<div class="flex justify-between">
					<span>Language ID</span>
					<span class="text-foreground font-medium">{library.languageId}</span>
				</div>
				<div class="flex justify-between">
					<span>Game Identifier</span>
					<span class="text-foreground font-medium">{library.gameId}</span>
				</div>
				<div class="flex justify-between">
					<span>Revision</span>
					<span class="text-foreground font-medium">{library.revision}</span>
				</div>
				<div class="flex justify-between">
					<span>Last Revised</span>
					<span class="text-foreground font-medium">{library.revisedOn.toLocaleDateString()}</span>
				</div>
			</div>
		</div>
	</Sidebar.Header>
	<Sidebar.Content class="flex flex-col gap-3 min-h-0 items-stretch grow px-4 py-4">
		<div>
			<div class="font-medium text-sm mb-2">Report</div>
			<div class="flex flex-col gap-1 text-[10px] uppercase tracking-wider text-muted-foreground">
				<div class="flex justify-between">
					<span>Verified</span>
					<span class="text-foreground font-medium">{stats.verifiedCount}</span>
				</div>
				<div class="flex justify-between">
					<span>Autogenerated</span>
					<span class="text-foreground font-medium">{stats.autogeneratedCount}</span>
				</div>
				<div class="flex justify-between">
					<span>Problems Detected</span>
					<span class="text-foreground font-medium">{stats.invalidCount}</span>
				</div>
				<div class="flex justify-between">
					<span>Bad Verifications</span>
					<span class="text-foreground font-medium">{stats.badVerificationCount}</span>
				</div>
			</div>
		</div>
		<Separator />
		<div class="flex flex-col min-h-0 grow">
			<div class="font-medium text-sm mb-2">Functions</div>
			<ScrollArea class="w-full max-w-full min-h-0 grow">
				<div class="grid grid-flow-row auto-rows-max w-full">
					{#each filteredData.entries as apiFunction}
						{@const functionEditor = editor.getFunction(apiFunction.name)}
						<Button
							variant="link"
							size={'sm'}
							class="justify-start font-normal text-muted-foreground"
							href={`/editor/${filteredData.languageId}/${apiFunction.name.toLowerCase()}`}
						>
							{#if functionEditor?.isInvalid}
								<div
									class="mr-2 h-2 w-2 shrink-0 rounded-full {functionEditor.isVerified
										? 'bg-red-600'
										: 'bg-amber-700'}"
									title={functionEditor.isVerified
										? 'This verified function has problems'
										: 'This function has problems'}
								></div>
							{:else if functionEditor?.isUnverified}
								<div
									class="mr-2 h-2 w-2 shrink-0 rounded-full bg-yellow-400"
									title="This function is unverified"
								></div>
							{/if}
							{truncateString(apiFunction.name, 25)}
						</Button>
					{/each}
				</div>
			</ScrollArea>
		</div>

		<div class="flex gap-2 shrink-0">
			<div class="relative w-full">
				<Search
					class="absolute left-2.5 top-[50%] -translate-y-[50%] h-4 w-4 text-muted-foreground pointer-events-none"
				/>
				<Input
					type="search"
					placeholder="Search..."
					class="w-full rounded-lg bg-background pl-8 pr-12"
					bind:value={searchTerm}
					bind:ref={inputElement}
				/>
				<div
					class="absolute right-2.5 top-[50%] -translate-y-[50%] flex items-center gap-1 rounded-md px-1 py-0.5 text-muted-foreground bg-muted text-xs pointer-events-none"
				>
					<Command class="w-3.5 h-3.5" />
					K
				</div>
			</div>
			<EditorFilters
				bind:showVerified
				bind:showAutogenerated
				bind:showProblems
				bind:showBadVerifications
			/>
		</div>
		<Separator />
		<div>
			<div class="font-medium text-sm mb-2">Actions</div>
			<div class="text-sm text-muted-foreground mb-3 italic">
				{#if stats.editedCount > 0}
					{stats.editedCount} function{stats.editedCount === 1 ? '' : 's'} edited.
				{:else}
					No changes applied.
				{/if}
			</div>
			<div class="flex gap-2 shrink-0">
				<Button variant="outline" size="sm" onclick={handleLoadFromJSON} class="flex-1 text-xs">
					Load JSON
				</Button>
				<Button
					variant="outline"
					size="sm"
					onclick={handleSaveToJSON}
					class="flex-1 text-xs"
					disabled={stats.editedCount === 0}
				>
					Save JSON
				</Button>
			</div>
		</div>
	</Sidebar.Content>

	<Sidebar.Footer
		class="text-muted-foreground text-xs inline-flex justify-between shrink-0 px-4 py-4"
	>
		A part of the GSCode project.
		<a
			href="https://ko-fi.com/blakintosh"
			target="_blank"
			rel="noreferrer"
			class="text-primary hover:underline"
		>
			Donate
		</a>
	</Sidebar.Footer>

	<Sidebar.Rail />
</Sidebar.Root>

<svelte:window onkeydown={handleKeyDown} onbeforeunload={handleBeforeUnload} />
