<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';

	import Filter from '@lucide/svelte/icons/filter';

	interface Props {
		showVerified: boolean;
		showProcessed: boolean;
		showAutogenerated: boolean;
		showProblems: boolean;
		showBadVerifications: boolean;
		showDeleted: boolean;
	}

	let {
		showVerified = $bindable(true),
		showProcessed = $bindable(true),
		showAutogenerated = $bindable(true),
		showProblems = $bindable(true),
		showBadVerifications = $bindable(true),
		showDeleted = $bindable(true)
	}: Props = $props();

	let hasActiveFilters = $derived(
		!showVerified ||
			!showProcessed ||
			!showAutogenerated ||
			!showProblems ||
			!showBadVerifications ||
			!showDeleted
	);

	/** Filter chip — teal fill when the group is shown, hairline outline when hidden. */
	const chipBase =
		'chip-cut px-3 py-1.5 text-left font-mono text-[10px] leading-none tracking-[.13em] uppercase transition-colors';
	const chipOn = `${chipBase} bg-primary text-primary-foreground`;
	const chipOff = `${chipBase} inset-edge text-dim hover:text-primary`;
</script>

<Popover.Root>
	<Popover.Trigger>
		{#snippet child({ props })}
			<Button variant="outline" size="icon" class="relative h-9 w-9 shrink-0" {...props}>
				<Filter class="h-4 w-4" />
				{#if hasActiveFilters}
					<span class="bg-primary absolute top-1 right-1 block size-[6px]"></span>
				{/if}
			</Button>
		{/snippet}
	</Popover.Trigger>
	<Popover.Content class="w-60 gap-3" align="end">
		<div class="type-label text-dim">Filter functions</div>
		<div class="flex flex-wrap gap-1.5">
			<button
				type="button"
				class={showVerified ? chipOn : chipOff}
				aria-pressed={showVerified}
				onclick={() => (showVerified = !showVerified)}
			>
				Verified
			</button>
			<button
				type="button"
				class={showProcessed ? chipOn : chipOff}
				aria-pressed={showProcessed}
				onclick={() => (showProcessed = !showProcessed)}
			>
				Processed
			</button>
			<button
				type="button"
				class={showAutogenerated ? chipOn : chipOff}
				aria-pressed={showAutogenerated}
				onclick={() => (showAutogenerated = !showAutogenerated)}
			>
				Autogenerated
			</button>
			<button
				type="button"
				class={showProblems ? chipOn : chipOff}
				aria-pressed={showProblems}
				onclick={() => (showProblems = !showProblems)}
			>
				Problems
			</button>
			<button
				type="button"
				class={showBadVerifications ? chipOn : chipOff}
				aria-pressed={showBadVerifications}
				onclick={() => (showBadVerifications = !showBadVerifications)}
			>
				Bad verifications
			</button>
			<button
				type="button"
				class={showDeleted ? chipOn : chipOff}
				aria-pressed={showDeleted}
				onclick={() => (showDeleted = !showDeleted)}
			>
				Deleted
			</button>
		</div>
	</Popover.Content>
</Popover.Root>
