<script lang="ts">
	import type { FunctionEditor } from '$lib/api-editor/function-editor.svelte';
	// @ts-ignore
	import TriangleAlert from 'lucide-svelte/icons/triangle-alert';
	// @ts-ignore
	import CircleHelp from 'lucide-svelte/icons/circle-help';
	import { Checkbox } from '$lib/components/ui/checkbox/index.js';
	import * as Tooltip from '$lib/components/ui/tooltip/index.js';
	import { Separator } from '$lib/components/ui/separator/index.js';

	interface Props {
		functionEditor: FunctionEditor;
	}

	let { functionEditor }: Props = $props();
</script>

<div>
	<div class="font-medium text-sm mb-2">Auto-Validation</div>
	<div class="flex flex-col gap-2">
		<div class="flex items-center gap-2 text-sm uppercase tracking-wider text-muted-foreground">
			{#if functionEditor.isValid && !functionEditor.isUnverified}
				<div class="size-3 rounded-full bg-green-500"></div>
				<span>Valid</span>
			{:else if functionEditor.isValid && functionEditor.isUnverified}
				<div class="size-3 rounded-full bg-yellow-400"></div>
				<span>Unverified</span>
			{:else if functionEditor.isVerified && !functionEditor.isValid}
				<div
					class="size-3 rounded-full {functionEditor.isVerified ? 'bg-red-600' : 'bg-amber-700'}"
				></div>
				<span class="text-foreground font-medium">Bad Verification</span>
			{:else}
				<div class="size-3 rounded-full bg-red-500"></div>
				<span class="text-foreground font-medium">Problems Detected</span>
			{/if}
		</div>
		{#if !functionEditor.isValid}
			<ul class="flex flex-col gap-2 mt-1 mb-2">
				{#each functionEditor.validationErrors as error}
					<li class="text-sm text-muted-foreground leading-tight flex gap-2 items-center">
						<TriangleAlert class="size-3 shrink-0 text-red-500" />
						<span>{error}</span>
					</li>
				{/each}
			</ul>
		{/if}
		{#if functionEditor.isUnverified && !functionEditor.isValid}
			<p class="text-sm text-muted-foreground">
				Manual review required to fix incorrect documentation.
			</p>
		{/if}
		{#if functionEditor.isUnverified && functionEditor.isValid}
			<p class="text-sm text-muted-foreground">
				Auto-validation pass does not guarantee documentation is correct. Manual review recommended.
			</p>
		{/if}
		{#if functionEditor.isVerified && !functionEditor.isValid}
			<p class="text-sm text-muted-foreground">
				Function does not pass requirements for verified status.
			</p>
		{/if}
	</div>

	<Separator class="my-6" />

	<div class="font-medium text-sm mb-3">Function Flags</div>
	<div class="flex flex-col gap-3">
		{#each [{ id: 'autogenerated', label: 'Autogenerated', tooltip: "This function was auto-generated from Treyarch's API and may contain errors." }, { id: 'verified', label: 'Verified', tooltip: 'This function was verified by a member of the community.' }, { id: 'broken', label: 'Broken', tooltip: 'This function is known to be broken or non-functional.' }, { id: 'malicious', label: 'Malicious', tooltip: 'This function is potentially malicious or dangerous to use.' }, { id: 'unlisted', label: 'Unlisted', tooltip: 'This function has been unlisted. It is unlikely to be functional and/or useful.' }] as flag}
			<div class="flex items-center justify-between gap-2">
				<label
					for={flag.id}
					class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer flex-grow"
				>
					{flag.label}
				</label>
				<div class="flex items-center gap-2">
					<Tooltip.Provider>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<CircleHelp class="size-3.5 text-muted-foreground" />
							</Tooltip.Trigger>
							<Tooltip.Content>
								<p class="max-w-xs text-xs">{flag.tooltip}</p>
							</Tooltip.Content>
						</Tooltip.Root>
					</Tooltip.Provider>
					<Checkbox
						id={flag.id}
						checked={functionEditor.function.flags.includes(flag.id)}
						onCheckedChange={() => functionEditor.toggleFlag(flag.id)}
					/>
				</div>
			</div>
		{/each}
	</div>
</div>
