/**
	GSCode Language Extension for Visual Studio Code
    Copyright (C) 2022 Blakintosh

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable @typescript-eslint/naming-convention */
import * as fs from "fs";
import * as vscode from "vscode";

export enum FunctionFlag {
	None = 0, // All OK
	AutoGenerated = 1, // This function has not been manually verified
	Deprecated = 2, // The function has been explicitly deprecated
	Broken = 3, // The function is not the above but is broken anyway
	Useless = 4, // This function serves no use in a *modding* context
}

export class GSCUtil {
    /**
     * Gets whether the given script path is a valid path.
     * @param path The path from TA_TOOLS_PATH or the user specified override, and this workspace.
     * @returns true if valid, false otherwise
     */
    static validateScriptPath(path: string): boolean {
        const workbenchConfig = vscode.workspace.getConfiguration('gsc');

        const validateExternals = workbenchConfig.get('dependencies.validateExternals');

        if(!validateExternals) {
            return true;
        }

        const overrideShared = workbenchConfig.get('dependencies.overrideSharedScriptsPath');

        // If we're in an open workspace, first try to find the script inside it
        const workspace = vscode.workspace.workspaceFolders;
        if(workspace !== undefined) {
            let wsFolder = workspace[0];
            let workspacePath = wsFolder.uri.path;

            // If we're not at the base folder, navigate to it
            const base = "/scripts/";
            if(workspacePath.lastIndexOf(base) !== -1) {
                workspacePath = workspacePath.substring(workspacePath.lastIndexOf(base) + base.length);
            }

            // Now see if this script is here
            if(fs.existsSync(workspacePath + "/" + path)) {
                return true;
            }
        } else {
            // We don't want to perform validation if the user hasn't opened a workspace
            return true;
        }
        
        // File not found in workspace, fallback to shared path
        const sharePath = (overrideShared !== "" ? overrideShared : process.env.TA_TOOLS_PATH + "/share/raw/");

        // Check if it exists in shared
        if(fs.existsSync(sharePath + path)) {
            return true;
        }

        // Not found
        return false;
    }
}